import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="p-4 border-b flex items-center gap-4">
					<a href="/" className="font-bold">Bunny's Events</a>
					<nav className="ml-auto flex gap-4">
						<a href="/login">Log in</a>
						<a href="/signup">Sign up</a>
					</nav>
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
